/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import { useEffect, useRef, useState } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import vertexShader from "./shaders/vertex.glsl";
import fragmentShader from "./shaders/fragment.glsl";

function Skull(props) {
  const { nodes } = useGLTF("/models/skull.glb");
  const groupRef = useRef();
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });

  const uniforms = {
    colorA: new THREE.Uniform(new THREE.Color("#f9b716")),
    colorB: new THREE.Uniform(new THREE.Color("#191919")),
    uTime: new THREE.Uniform(0),
  };

  const shaderMaterial = new THREE.ShaderMaterial({
    uniforms: uniforms,
    vertexShader,
    fragmentShader,
  });

  // Track mouse movement
  useEffect(() => {
    const handleMouseMove = (event) => {
      // Calculate normalized mouse position (-1 to 1)
      setMousePosition({
        x: (event.clientX / window.innerWidth) * 2 - 1,
        y: -(event.clientY / window.innerHeight) * 2 + 1,
      });
    };

    if (window.innerWidth < 600) {
      groupRef.current.scale.set(0.7, 0.7, 0.7);
    }

    window.addEventListener("mousemove", handleMouseMove);
    return () => {
      window.removeEventListener("mousemove", handleMouseMove);
    };
  }, []);

  useFrame((state) => {
    uniforms.uTime.value = state.clock.elapsedTime;

    if (groupRef.current) {
      // Create subtle rotation based on mouse position
      const targetRotationX = mousePosition.y * 0.1; // Vertical movement (look up/down)
      const targetRotationY = mousePosition.x * 0.1; // Horizontal movement (look left/right)

      // Smooth interpolation for more natural movement
      groupRef.current.rotation.x = THREE.MathUtils.lerp(
        groupRef.current.rotation.x,
        targetRotationX,
        0.05
      );

      groupRef.current.rotation.y = THREE.MathUtils.lerp(
        groupRef.current.rotation.y,
        targetRotationY,
        0.05
      );
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null} position={[0, -1, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bad_skull.geometry}
        material={nodes.bad_skull.material}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.065}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.eyes.geometry}
        material={shaderMaterial}
        position={[1.799, 2.764, 1.97]}
        scale={1.601}
      />
    </group>
  );
}

useGLTF.preload("/models/skull.glb");

export default Skull;
